// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrxwxvyihnivgkpydanh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyeHd4dnlpaG5pdmdrcHlkYW5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NjA5MzgsImV4cCI6MjA1OTIzNjkzOH0.i966BLtINCy1Z91nxit-ywhjjSbRVkviazi8qhgqrJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);